# Multi-stage build: First stage for building Go app
#FROM cgr.dev/chainguard/go AS builder
FROM golang:1.23.4-alpine AS builder
WORKDIR /src

# Copy source code
COPY ./web ./web
COPY ./pkg ./pkg
COPY ./mcp ./mcp
COPY ./opsagent ./opsagent

# Copy the workspace file
COPY go.work ./go.work

# Download Files
WORKDIR /src/web
RUN go mod download

# WORKDIR /src

# Build the WASM Application
RUN GOOS=js GOARCH=wasm go build -o public/app.wasm -buildvcs=false .

# Build the Go application from web/main.go
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /src/webapp ./main.go

# ADD wget
RUN apk add wget

# BUILD SERVER IMAGE
FROM cgr.dev/chainguard/go:latest

WORKDIR /app

# IF NEEDED ADD wget
COPY --from=builder /usr/bin/wget /usr/bin/wget
# Copy the built binary from builder stage
COPY --from=builder /src/webapp /app/webapp

# Copy public folder contents
COPY --from=builder /src/web/public/ /app/public/

EXPOSE 8000

ENTRYPOINT ["/app/webapp"]
