FROM neo4j:5-community

ENV NEO4J_AUTH=neo4j/password
ENV NEO4J_dbms_default__database=bigfoot
ENV NEO4J_dbms_security_procedures_unrestricted=apoc.*
ENV NEO4J_dbms_security_procedures_allowlist=apoc.*

EXPOSE 7474 7687

VOLUME /data
VOLUME /logs
VOLUME /import
VOLUME /plugins
