services:
  neo4j:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db1
    ports:
      - "7474:7474"  # HTTP (for browser access)
      - "7687:7687"  # Bolt (for application connections)
    environment:
      - NEO4J_PASSWORD=${DB_ADMIN}
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - app-network
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: webbuild
    container_name: web-app
    ports:
      - "8000:8000"  # Adjust port based on your app
    environment:
      # Database connection using service name
      - DB_URI=bolt://neo4j:7687
      - DB_ADMIN=${DB_ADMIN}
      - MODE=dev
      - SESSION_KEY=${SESSION_KEY}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
      - DB_USER=${DB_USER}
      - MCP_MODE=${MCP_MODE}
      - LLM_GATEWAY_URL=http://agentgateway:3001
      - MCP_GATEWAY_URL=http://agentgateway:3000
      - JWT_SECRET=${JWT_SECRET}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #depends_on:
    #  neo4j:
    #    condition: service_healthy
    networks:
      - app-network
  mcp-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: mcpbuild
    container_name: mcp-app
    ports:
      - "8081:8081"  # Adjust port based on your app
    environment:
      - DB_URI=bolt://neo4j:7687
      - DB_ADMIN=${DB_ADMIN}
      - MODE=dev
      - DB_USER=${DB_USER}
      - MCP_MODE=${MCP_MODE}
    networks:
      - app-network
  agentgateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: agentgateway
    ports:
      - "3000:3000"  # MCP endpoint
      - "3001:3001"  # Bedrock AI endpoint
      - "3002:3002"  # Eval AI endpoint
      - "15000:15000"  # UI for Agent Gateway
    environment:
      - AWS_REGION=us-east-1
      - MCP_HOST=http://mcp-app:8081/mcp
      - LLM_MODEL=${LLM_MODEL}
      - AWS_BEARER_TOKEN_BEDROCK=${AWS_BEARER_TOKEN_BEDROCK}
      - ADMIN_ADDR=0.0.0.0:15000
      - GWAY_HOST=agentgateway
      - OTEL_ADDR=http://arizeai:4317
    networks:
      - app-network

  arizeai:
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006" # Front End
      - "4317:4317" # OLTP Port 
    container_name: arizeai
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: my-app-network

volumes:
  neo4j_data:
    name: neo4j_data
  neo4j_logs:
    name: neo4j_logs