config:
  tracing:
    otlpEndpoint: http://arizeai:4317
    randomSampling: 1.0
    fields:
      add:
        span.name: '"openai.chat"'
        openinference.span.kind: '"LLM"'
        llm.system: 'llm.provider'
        llm.input_messages: 'flatten_recursive(llm.prompt.map(c, {"message": c}))'
        llm.output_messages: 'flatten_recursive(llm.completion.map(c, {"role":"assistant", "content": c}))'
        llm.token_count.completion: 'llm.outputTokens'
        llm.token_count.prompt: 'llm.inputTokens'
        llm.token_count.total: 'llm.totalTokens'
binds:
- port: 3000
  listeners:
  - protocol: HTTP
    name: bigfootmcp
    hostname: agentgateway
    routes:
    - policies:
        cors:
          allowOrigins:
          - "*"
          allowHeaders:
          - "*"
        #requestHeaderModifier:
        #  add:
        #    content-type: application/json
        #    accept: application/json, text/event-stream
        #    mcp-protocol-version: 2025-06-18
      backends:
      - mcp:
          targets:
          - name: mcp
            mcp:
              host: ${MCP_HOST}
- port: 3001
  listeners:
  - protocol: HTTP
    name: brock
    hostname: ${GWAY_HOST}
    routes:
    - backends:
      - ai:
          name: bedrock
          provider:
            bedrock:
              region: us-east-1
              model: ${LLM_MODEL}
      policies:
        backendAuth:
          key: ${AWS_BEARER_TOKEN_BEDROCK}